name: App PHP

on: [push]

jobs:
  test-app:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SetUp PHP
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdom pdo_mysql

      - name: Install Packages
        run: composer install --no-interaction

