name: App Runners

on: [push]

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: ls
        run: ls

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Notificacion Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          author_name: "Action"
          fields: repo,message,commit,author,action,eventName