name: App Slack

on: push

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: drilonrecica/action-slack-notify@0.0.3
      env:
        SLACK_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
