name: App Slack

on: push

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: gymshark/slack-notifier-action@v1.0.2
      with:
        webhook_url: 'https://hooks.slack.com/services/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' 
